### ISSUE TITLE
Request error: ECONNRESET

### ISSUE THREAD

**Issue by sunlery** [microsoft/sqltoolsservice#1279]
Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: win32, x86_64 (Windows)

Installing SQL tools service to d:\TurboLaunch\Sorft\Code\VSCodePlugins\extensions\ms-mssql.mssql-1.11.0\sqltoolsservice\3.0.0-release.139\Windows.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/v3.0.0-release.139/microsoft.sqltools.servicelayer-win-x64-net5.0.zip
[ERROR] Error: Request error: ECONNRESET

**Comment by kburtram** [comment]
@sunlery `ECONNRESET` is a TCP error saying that the connection has been disconnected (i.e. reset).  The vscode-mssql uses a common npm module for file download so the problem is likely in the network.  If you restart vscode the extension should attempt the download again.   If the issue is persistent please verify you are able to successfully download the file referenced in the message.

Please let us know if there is anything else we can assist with regarding this error.

**Comment by sethalewis** [comment]
I've run into the same issue above. When I try to download the referenced .zip file, it downloads as an empty folder. I am not sure how to fix this issue. Any assistance is greatly appreciated.

**Comment by Charles-Gagnon** [comment]
@sethalewis If that link isn't working then it sounds like some network issue on your end - are you behind a proxy that may be blocking it or something?

**Comment by sethalewis** [comment]
@Charles-Gagnon You were right. I was trying to install on my company network. Once I retried on my home network, it worked properly. Thanks for your help!

**Comment by sunlery** [comment]
@kburtram Today, it worked properly. Thanks for your help!
