### ISSUE TITLE
Code analysis feature

### ISSUE THREAD

**Issue by d0ntth1nc** [Microsoft/sqltoolsservice#159]
Hello,

I think that static code analysis will be a great feature for the extension. Is it possible to make analyzer like eslint using the current SQL parser?

**Comment by kevcunnane** [comment]
@d0ntth1nc this is an excellent suggestion. We support static code analysis rules in the Data-Tier Application Framework (Dacfx) - see https://github.com/Microsoft/DACExtensions/tree/master/RuleSamples for samples of this. It's available in SQL Projects for Visual Studio, and the APIs support analysis of live databases.

The right solution would be to port DacFx over to .Net Core and support this through the tools service. This isn't planned for the next few sprints but we do have this as a larger feature on our overall backlog. Hearing feedback from users like yourself helps prioritize these issues.

**Comment by AntonBozhinov** [comment]
I would love to see that feature too.

**Comment by kevcunnane** [comment]
@d0ntth1nc, @AntonBozhinov  - I am moving this to our main repository with issue # https://github.com/Microsoft/vscode-mssql/issues/413. We're tracking all our user asks there, so I think it makes more sense to track in one place. I'm going to close this issue since to avoid duplication. Thanks again.
