### ISSUE TITLE
Difference between microsoft.sqltools.credentials and servicelayer

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/sqltoolsservice#371]
Just for clarification!  What's the difference between the microsoft.sqltools.credentials and microsoft.sqltools.servicelayer? Should I install both of them? 

Thanks,
:)

**Comment by kevcunnane** [comment]
The ServiceLayer exe is best for most scenarios.

- Microsoft.SqlTools.Credentials is a stripped-down app that mostly serves to support password management by our tools. Its focus is supporting save/read password requests when passed a connection profile. This is useful since we need to securely store a password in Credential Vault (Windows), KeyChain (macOS), or an ACL'd file (Linux, sadly no better "works everywhere" solution for now)
- Microsoft.SqlTools.Service supports all our functionality - intellisense, query execution, plus some in-progress work on new features. Currently both the VSCode-MSSQL extension and the mssql-scripter commandline "schema and data dumper" utility use this to support their scenarios.

If this answers your question, please close out the issue, thanks!

**Comment by MaximoTrinidad** [comment]
Hi @kevcunnane,

Awesome! That works. I will closed this one.
Thanks for the quick response,
Max
