### ISSUE TITLE
Where can I find Microsoft.SqlServer.XEvent.Linq.QueryableXEventData?

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/sqltoolsservice#807]
Looks like `Microsoft.SqlServer.XEvent.Linq.dll` has been removed. It was found in previous versions, including `microsoft.sqlserver.sqlmanagementobjects.150.18040.0-preview`

Either way, I'm looking for QueryableXEventData which is awesome and useful. When I try to load the DLL from old versions including `microsoft.sqlserver.sqlmanagementobjects.150.18040.0-preview`, I get 

```
Add-Type : Could not load file or assembly 'Microsoft.SqlServer.Xe.Core.dll' or one of its dependencies. The specified module could not be found.
```

How can I get this class back? I'm using this version of SMO

![image](https://user-images.githubusercontent.com/8278033/57449797-203e7580-725d-11e9-95e9-55c0dd00fee0.png)

Thanks much,
Chrissy

**Comment by kburtram** [comment]
@shueybubbles think looks like another question you may be able to help with?

**Comment by shueybubbles** [comment]
We removed it from the SMO package for various reasons, mainly because it's native code and we're trying to move toward a fully managed package and because the tools team doesn't really own it. I've tried to get the XEvent team to own publishing their own package.

Have you tried using 140.17279.0? It has both DLLs in it.
 Directory of I:\Microsoft.SqlServer.SqlManagementObjects.140.17279.0\runtimes\win-x64\native

07/19/2018  04:25 PM    <DIR>          .
07/19/2018  04:25 PM    <DIR>          ..
06/27/2018  06:16 PM           278,688 Microsoft.SqlServer.BatchParser.dll
06/27/2018  06:16 PM            65,208 Microsoft.SqlServer.Xe.Core.dll
06/27/2018  06:16 PM           304,352 Microsoft.SqlServer.XEvent.Linq.dll
               3 File(s)        648,248 bytes

AFAIK there's nothing functionally different between the 150 and the 140 versions

**Comment by potatoqualitee** [comment]
Thanks, sorry I posted in the wrong repo. Is there a github where we can chat or is it just azure feedback? Either way, can you message me on the SQL Slack? I just tried those and I'm still getting similar issues

```
 Cannot find type [Microsoft.SqlServer.XEvent.Linq.QueryableXEventData]
```

I'd like to better understand SMO's relationship to the XE commands and prereqs, etc. Thanks much.

**Comment by The-doubtless-coder** [comment]
hey! I don't get what is happening here but what could be a quick solution to the above error

**Comment by ywlei** [comment]
Hi, is QueryableXEventData in Microsoft.SqlServer.XEvent.Linq.dll supported anywhere now?
