### ISSUE TITLE
[Microsoft.SqlServer.Management.Smo.Server] Class issue with Platform vs HostPlatform

### ISSUE THREAD

**Issue by wsmelton** [microsoft/sqltoolsservice#866]
Running this code when on Windows or Mac against a the SQL Server Docker container returns Platform as `NT x64`:

```powershell
$loc = Get-InstalledModule -Name sqlserver | select -first 1 -Property InstalledLocation
Add-Type -Path "$($loc.InstalledLocation)\coreclr\Microsoft.SqlServer.Smo.dll"
Add-Type -Path "$($loc.InstalledLocation)\coreclr\Microsoft.SqlServer.ConnectionInfo.dll"
Add-Type -Path "$($loc.InstalledLocation)\coreclr\Microsoft.SqlServer.Management.Sdk.Sfc.dll"
$servername = "localhost,1411"
$server = New-Object Microsoft.SqlServer.Management.Smo.Server $servername 
$message = "Enter the SQL Login credentials for the SQL Server" 
$server.ConnectionContext.LoginSecure = $false
$sqllogin = Get-Credential -Message $message 
$server.ConnectionContext.set_Login($sqllogin.username)
$server.ConnectionContext.set_SecurePassword($sqllogin.Password)
$server | select-object HostPlatform, Platform
```

Another person has shown this same result when he runs it on Mac with Docker for Mac container running.

Ref: sqlcollaborative/dbatools#6038

**Comment by shueybubbles** [comment]
"Platform" is simply what xp_msver returns
Since sqlserver.exe is running on a Windows emulator on Linux, that's what it will return.
We added HostPlatform so new apps could distinguish the real host OS from the emulator.
HostPlatform is based on a new view, sys,dm_os_host_info, which is meant to replace xp_msver for new apps.
